### ISSUE TITLE
error compiling viper-web

### ISSUE THREAD

**Issue by mikojacko** [grdw/viper-client#39]
I'm totally new in rust language and i've followed some guides.
After modified the .env file with the correct vaules
TOKEN=2c7dcxxxxxxxxxxxxxx0a
DOORBELL_IP=192.168.188.97
DOORBELL_PORT=64100

with "cargo run" or "cargo build" commands  i got this errors:

   Compiling viper-web v0.1.0 (C:\viper-client-main\viper-client-main\viper-web)
error[E0608]: cannot index into a value of type `AuthResponse`
   --> src\main.rs:114:17
    |
114 |     if auth_json["response-code"] == 200 {
    |                 ^^^^^^^^^^^^^^^^^

error[E0608]: cannot index into a value of type `ConfigurationResponse`
   --> src\main.rs:117:28
    |
117 |         Ok(web::Json(config["vip"].clone()))
    |                            ^^^^^^^

error[E0608]: cannot index into a value of type `AuthResponse`
   --> src\main.rs:133:17
    |
133 |     if auth_json["response-code"] == 200 {
    |                 ^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src\main.rs:146:26
    |
146 |         client.open_door(&thingy)?;
    |                --------- ^^^^^^^ expected `&VipResponse`, found `&Value`
    |                |
    |                arguments to this method are incorrect
    |
    = note: expected reference `&VipResponse`
               found reference `&Value`
note: method defined here
   --> C:\viper-client-main\viper-client-main\src\lib.rs:134:12
    |
134 |     pub fn open_door(&mut self, vip: &VipResponse) -> Result<(), std::io::Error> {
    |            ^^^^^^^^^

Some errors have detailed explanations: E0308, E0608.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `viper-web` (bin "viper-web") due to 4 previous errors

I've already updated cargo and rust.

Can you give me some help?

Thanks

**Comment by grdw** [comment]
I haven't looked at the web one in ages. :sweat_smile:  I mostly just look at it from the terminal. I guess some of the structs changed in the mean time. I'll take a look at it; it doesn't seem too hard to fix.
